#Avinash Ramu, WUSTL
#Script to plot ROC using WGS validation data.
#Arg1 - file generated by calling ~/Scripts/paperScripts/callCompare_WGS.sh

  args<-commandArgs()	
  f<-args[6]
  print(f)
  source("~/Scripts/arrange.R")
  caller<-read.table(f, head = T)
  pdf("ROC_WGS_g_s.pdf")
  require("ggplot2")
  p_g <-ggplot(caller, aes(x = FDR, y = g_sens)) + geom_path() + geom_point() + opts( title = "Denovo caller comparison - Whole genome sequencing" ) + ylab("sensitivity (germline)")
  p_s <-ggplot(caller, aes(x = FDR, y = s_sens)) + geom_path() + geom_point() +  ylab("sensitivity (somatic)")
  arrange(p_g, p_s, ncol = 1)
  dev.off()