#ipFile format - chr pos reads_ref reads_alt (reads_ref+reads_alt)
plotFits_IDs_3 <- function(ipFile1, ipFile2, ipFile3, opFile) 
{
        require("ggplot2")
        t1<-read.table(ipFile1, sep = "\t")
	t2<-read.table(ipFile2, sep = "\t")
	t3<-read.table(ipFile3, sep = "\t")
	#require(ggplot2)
	source("~/Scripts/var_bin.R")
	source("~/Scripts/var_poisson.R")
	source("~/Scripts/betaBinomial.R")
	source("~/Scripts/var_betbin.R")
	a1<-aggregate(t1$V4, by=list(t1$V5), FUN=var)
	a1<-na.omit(a1)
	head(a1)
	a2<-aggregate(t2$V4, by=list(t2$V5), FUN=var)
	a2<-na.omit(a2)
	a3<-aggregate(t3$V4, by=list(t3$V5), FUN=var)
	a3<-na.omit(a3)
	write.table(a1, file = paste(opFile, "_1_variance", sep = ""), sep = "\t", quote = F, row.names = F)
	write.table(a2, file = paste(opFile, "_2_variance", sep = ""), sep = "\t", quote = F, row.names = F)
	write.table(a3, file = paste(opFile, "_3_variance", sep = ""), sep = "\t", quote = F, row.names = F)
	ab<-as.vector(bbFit(n = t1$V5, k = t1$V4))
	pdf(paste(opFile, ".pdf", sep = ""))
	print(ab[1])
	print(ab[2])
	class(ab)
	plot(a1$Group.1, a1$x, type = "l", xlim = c(0, 200), ylim = c(0, 3000), xlab = "Ref+Alt Count", ylab = "Var of Alt Count", main = opFile)
	points(a2$Group.1, a2$x, col = "yellow", type = "l")
	points(a3$Group.1, a3$x, col = "pink", type = "l")
	points(a1$Group.1, var_betbin(n = a1$Group.1, a = ab[1], b = ab[2]), type = "l", col= "red")
	points(a1$Group.1, var_poisson(n = a1$Group.1, lambda = 0.5), type = "l", col = "blue")
	points(a1$Group.1, var_bin(n = a1$Group.1, p = 0.5), type = "l", col = "green")
	legend(x = "topright", c("Binomial", "Poisson", "BetaBinomial - fit on NA12878 Variance", "Exome Data"),
	         lty=c(1,1), # gives the legend appropriate symbols (lines)
             lwd=c(2.5,2.5),
             col=c("green","blue", "red", "black"))
	legend(x = "topleft", c("NA12878", "NA12891", "NA12892"),
	         #pch = 1, # gives the legend appropriate symbols (lines)
             lty=c(1,1), # gives the legend appropriate symbols (lines)
             lwd=c(2.5,2.5),
             col=c("black","yellow", "pink"))
	dev.off()
        NA12878<-cbind(a1$Group.1, as.numeric(a1$x), "NA12878")
        NA12891<-cbind(a2$Group.1, as.numeric(a2$x), "NA12891")
        NA12892<-cbind(a3$Group.1, a3$x, "NA12892")
        Variance_Beta_Binomial<-cbind(a1$Group.1, var_betbin(n = a1$Group.1, a = ab[1], b = ab[2]), "Beta_Binomial")
        Variance_Poisson<-cbind(a1$Group.1, var_poisson(n = a1$Group.1, lambda = 0.5), "Poisson")
        Variance_Binomial<-cbind(a1$Group.1, var_bin(n = a1$Group.1, p = 0.5), "Binomial")

        t<-as.data.frame(rbind(NA12878, NA12891, NA12892, Variance_Beta_Binomial, Variance_Poisson, Variance_Binomial))
        colnames(t)<-c("RA", "V_A", "M")
        t$V_A<-as.numeric(as.character(t$V_A))
        t$RA<-as.numeric(as.character(t$RA))
        print(head(t))
#        ggplot(data = t, aes(x=RA, y=V_A)) + geom_line(aes(col = M)) +scale_x_continuous(limits = c(0,200)) + scale_y_continuous(limits = c(0,500))
        ggplot(data = t, aes(x=RA, y=V_A)) + geom_line(aes(col = M)) + scale_x_continuous(limits = c(0,200)) +scale_y_continuous(limits = c(0,3000)) + theme(legend.title = element_blank() ) + xlab("Reference + Alternate allele count") + ylab("Variance of alternate allele count") + coord_fixed(ratio = 200/3000)
        ggsave("./WEx_CEU_Indels_ggplot.pdf")



}
